// <auto-generated />
using GameNewsWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameNewsWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310134430_UpdateGamesSeed")]
    partial class UpdateGamesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameNewsWeb.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "RPG",
                            ImageUrl = "assets/img/image 1.png",
                            Platform = "PC",
                            Price = 2500m,
                            Rating = 4.7999999999999998,
                            Title = "Split Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "RPG",
                            ImageUrl = "assets/img/image 2.png",
                            Platform = "PC, PS5, Xbox",
                            Price = 3500m,
                            Rating = 4.5999999999999996,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "MOBA",
                            ImageUrl = "assets/img/image 3.png",
                            Platform = "PC",
                            Price = 0m,
                            Rating = 4.7000000000000002,
                            Title = "Dota 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
