// <auto-generated />
using GameNewsWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameNewsWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317080728_AddDescriptionRequirements")]
    partial class AddDescriptionRequirements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameNewsWeb.Models.Announce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "RPG",
                            LinkUrl = "announce-1.html",
                            Platform = "PC",
                            Summary = "Студия анонсировала новый проект в жанре фэнтези...",
                            TimeText = "сегодня в 10:00",
                            Title = "Анонс новой игры от CD Projekt RED"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Adventure",
                            LinkUrl = "announce-2.html",
                            Platform = "PS5",
                            Summary = "Новая часть серии выйдет в следующем году...",
                            TimeText = "вчера в 10:00",
                            Title = "Ubisoft представила трейлер Assassin's Creed"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Strategy",
                            LinkUrl = "announce-3.html",
                            Platform = "Xbox",
                            Summary = "Первое крупное дополнение к космической RPG...",
                            TimeText = "позавчера в 10:00",
                            Title = "Bethesda анонсировала Starfield DLC"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Adventure",
                            LinkUrl = "announce-4.html",
                            Platform = "Switch",
                            Summary = "Разработчики показали геймплей и дату релиза...",
                            TimeText = "4 дня назад",
                            Title = "Новая кооперативная игра на Switch"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Strategy",
                            LinkUrl = "announce-5.html",
                            Platform = "PC",
                            Summary = "Анонсирована новая стратегия с упором на кампанию...",
                            TimeText = "неделю назад",
                            Title = "Тактическая стратегия для PC"
                        });
                });

            modelBuilder.Entity("GameNewsWeb.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Split Fiction — сюжетная RPG в научно‑фантастическом сеттинге.",
                            Genre = "RPG",
                            ImageUrl = "assets/img/image 1.png",
                            Platform = "PC",
                            Price = 2500m,
                            Rating = 4.7999999999999998,
                            Requirements = "ОС: Windows 10 64-bit; CPU: i5/Ryzen 5; RAM: 16 GB; GPU: GTX 1060/RX 580; Место: 80 GB",
                            Title = "Split Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cyberpunk 2077 — ролевая игра в открытом мире Найт‑Сити.",
                            Genre = "RPG",
                            ImageUrl = "assets/img/image 2.png",
                            Platform = "PC, PS5, Xbox",
                            Price = 3500m,
                            Rating = 4.5999999999999996,
                            Requirements = "ОС: Windows 10 64-bit; CPU: i7/Ryzen 5; RAM: 12 GB; GPU: GTX 1060 6GB/RX 580 8GB; Место: 70 GB",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dota 2 — командная MOBA с глубокой механикой и киберспортом.",
                            Genre = "MOBA",
                            ImageUrl = "assets/img/image 3.png",
                            Platform = "PC",
                            Price = 0m,
                            Rating = 4.7000000000000002,
                            Requirements = "ОС: Windows 10 64-bit; CPU: 2.8 GHz dual‑core; RAM: 8 GB; GPU: GeForce 8600/Radeon HD2600; Место: 50 GB",
                            Title = "Dota 2"
                        });
                });

            modelBuilder.Entity("GameNewsWeb.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "assets/img/Rectangle 8.png",
                            LinkUrl = "news-1.html",
                            Summary = "Хакеры удалили Denuvo из Tourist Bus Simulator и обещают...",
                            TimeText = "сегодня в 13:00",
                            Title = "SKIDROW наконец-то сделали это..."
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "assets/img/Rectangle 10.png",
                            LinkUrl = "news-2.html",
                            Summary = "Подробности апдейта и совместимости GPU...",
                            TimeText = "сегодня в 11:40",
                            Title = "Время апгрейда: Silent Hill f не работает на RTX 5090"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "assets/img/Rectangle 12.png",
                            LinkUrl = "news-3.html",
                            Summary = "«Лучшая научно-фантастическая игра» на Galaxy Sci-Fi...",
                            TimeText = "вчера в 10:00",
                            Title = "Cyberpunk 2077 получила награду"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "assets/img/Rectangle 10.png",
                            LinkUrl = "news-4.html",
                            Summary = "Собрали самые интересные инди-релизы недели...",
                            TimeText = "3 дня назад в 15:30",
                            Title = "Подборка свежих инди-игр недели"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
